services:
  flask_app:
    container_name: flask_app
    image: webrota/flask_live_app:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@localhost:5432/position
      - JWT_SECRET_KEY=secret_key
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  react_app:
    container_name: react_app
    build:
      context: ./frontend # substitua pelo caminho real para o diretório do seu app React
      dockerfile: Dockerfile # supondo que você tenha um Dockerfile configurado para o React
    ports:
      - "3000:3000"
    depends_on:
      - flask_app

volumes:
  pgdata: {}
    